-- supabase_phase31b_auto_lost_fix.sql
--
-- Phase 31B — fix the auto-Lost regression introduced by Phase 30C
-- rev2's tap-to-log Call / WhatsApp / Email buttons.
--
-- Owner reported (9 May 2026): "when I changed status it's going
-- Lost". Lead ended up Lost without explicit user action.
--
-- Root cause: the Phase 12 trigger lead_activity_after_insert()
-- auto-Lost any lead after 3 contact attempts whose outcome is
-- 'null' or in ('neutral','negative'). Phase 30C rev2 added fast-path
-- buttons that fire-and-forget activity inserts with outcome=null
-- (rep clicked the action; we have no info on how the conversation
-- went). Three clicks → lead Lost. Bad.
--
-- Fix: only count explicit NEGATIVE outcomes toward the auto-Lost
-- threshold AND raise the bar from 3 to 5. Null / neutral outcomes
-- no longer drag the lead toward Lost — they only bump the
-- contact_attempts_count for tracking.
--
-- Side effect kept: contact_attempts_count and last_contact_at still
-- update on every call/whatsapp/email/meeting/site_visit insert
-- (rep stats remain accurate; only the Lost auto-flip changes).
--
-- Idempotent — replaces the existing function in place.

-- -------------------------------------------------------------------------
-- lead_activity_after_insert REMOVED from this file (Phase 178).
-- Canonical: db/functions/lead_activity_after_insert.sql
-- Do NOT re-add it here. Edit the canonical file only (§71). Trigger wiring
-- (trg_lead_activity_after_insert) stays in phase12 (+ idempotent re-creates).
-- -------------------------------------------------------------------------

-- VERIFY:
-- The trigger is unchanged structurally (still AFTER INSERT on
-- lead_activities); we just replaced the function body. Existing
-- contact_attempts_count values stay as-is — only future inserts
-- use the new logic.
--
-- To check: SELECT pg_get_functiondef('public.lead_activity_after_insert'::regproc);
--   should show v_negative_count + the new threshold.
