-- ============================================================
-- UNTITLED OS — COMBINED MIGRATIONS (1-of-1 PASTE)
-- ============================================================
-- Generated by concatenating 10 individual migration files in
-- the apply-order from ARCHITECTURE.md §5.
-- Run ONCE in a fresh Supabase project's SQL Editor.
-- ============================================================


-- ============================================================
-- BEGIN: supabase_schema.sql
-- ============================================================
-- =====================================================
-- UNTITLED ADFLUX — COMPLETE SUPABASE SCHEMA (v2, fresh)
-- =====================================================
--
-- This is ONE file. Run it once in a brand new Supabase project's
-- SQL Editor. It creates everything: tables, triggers, RLS policies,
-- and turns on realtime for the dashboard.
--
-- AFTER you run this, go to the DEPLOY_GUIDE.md (Section 3, Step 4)
-- to seed your admin user. That seed step is a SEPARATE SQL snippet
-- — it's NOT in this file because it needs the UUID that Supabase
-- Auth generates when you create your admin login.
-- =====================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =====================================================
-- TABLES
-- =====================================================

CREATE TABLE users (
  id                uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  name              text NOT NULL,
  email             text UNIQUE NOT NULL,
  role              text NOT NULL CHECK (role IN ('admin', 'sales')),
  is_active         boolean DEFAULT true,
  created_at        timestamptz DEFAULT now()
);

CREATE TABLE cities (
  id                uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  name              text NOT NULL,
  station_name      text,
  grade             text CHECK (grade IN ('A', 'B', 'C')),
  screens           integer DEFAULT 1,
  screen_size_inch  integer,
  monthly_rate      numeric DEFAULT 0,
  offer_rate        numeric DEFAULT 0,
  impressions_day   integer DEFAULT 0,
  impressions_month integer DEFAULT 0,
  unique_viewers    integer DEFAULT 0,
  photo_url         text,
  is_active         boolean DEFAULT true,
  created_at        timestamptz DEFAULT now()
);

CREATE TABLE quotes (
  id                    uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  quote_number          text UNIQUE NOT NULL,
  client_name           text NOT NULL,
  client_company        text,
  client_phone          text,
  client_email          text,
  client_gst            text,
  client_address        text,
  client_notes          text,
  duration_months       integer DEFAULT 1,
  duration_mult         numeric DEFAULT 1,
  subtotal              numeric DEFAULT 0,
  gst_amount            numeric DEFAULT 0,
  total_amount          numeric DEFAULT 0,
  revenue_type          text DEFAULT 'new' CHECK (revenue_type IN ('new', 'renewal')),
  status                text DEFAULT 'draft' CHECK (status IN ('draft','sent','negotiating','won','lost')),
  created_by            uuid REFERENCES users(id),
  sales_person_name     text,
  created_at            timestamptz DEFAULT now(),
  updated_at            timestamptz DEFAULT now(),
  follow_up_date        date,
  follow_up_done        boolean DEFAULT false,
  campaign_start_date   date,
  campaign_end_date     date
);

CREATE TABLE quote_cities (
  id                uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  quote_id          uuid REFERENCES quotes(id) ON DELETE CASCADE,
  city_id           uuid REFERENCES cities(id),
  city_name         text NOT NULL,
  screens           integer DEFAULT 1,
  grade             text,
  listed_rate       numeric DEFAULT 0,
  offered_rate      numeric DEFAULT 0,
  override_reason   text,
  campaign_total    numeric DEFAULT 0,
  duration_months   integer DEFAULT 1
);

CREATE TABLE payments (
  id                uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  quote_id          uuid REFERENCES quotes(id) ON DELETE CASCADE,
  amount_received   numeric NOT NULL,
  payment_mode      text CHECK (payment_mode IN ('NEFT','RTGS','UPI','Cheque','Cash')),
  payment_date      date DEFAULT CURRENT_DATE,
  reference_number  text,
  payment_notes     text,
  received_by       uuid REFERENCES users(id),
  is_final_payment  boolean DEFAULT false,
  created_at        timestamptz DEFAULT now()
);

CREATE TABLE staff_incentive_profiles (
  id                    uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id               uuid UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  monthly_salary        numeric DEFAULT 0,
  sales_multiplier      numeric DEFAULT 5,
  new_client_rate       numeric DEFAULT 0.05,
  renewal_rate          numeric DEFAULT 0.02,
  flat_bonus            numeric DEFAULT 10000,
  join_date             date DEFAULT CURRENT_DATE,
  last_increment_date   date,
  is_active             boolean DEFAULT true
);

CREATE TABLE monthly_sales_data (
  id                    uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  staff_id              uuid REFERENCES users(id) ON DELETE CASCADE,
  month_year            text NOT NULL,
  new_client_revenue    numeric DEFAULT 0,
  renewal_revenue       numeric DEFAULT 0,
  updated_at            timestamptz DEFAULT now(),
  UNIQUE(staff_id, month_year)
);

CREATE TABLE follow_ups (
  id                uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  quote_id          uuid REFERENCES quotes(id) ON DELETE CASCADE,
  assigned_to       uuid REFERENCES users(id),
  follow_up_date    date NOT NULL,
  note              text,
  is_done           boolean DEFAULT false,
  done_at           timestamptz,
  created_at        timestamptz DEFAULT now()
);

CREATE TABLE incentive_settings (
  id                    uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  default_multiplier    numeric DEFAULT 5,
  new_client_rate       numeric DEFAULT 0.05,
  renewal_rate          numeric DEFAULT 0.02,
  default_flat_bonus    numeric DEFAULT 10000,
  updated_at            timestamptz DEFAULT now()
);

-- Seed the single global incentive settings row
INSERT INTO incentive_settings (id) VALUES (uuid_generate_v4());

-- =====================================================
-- FUNCTIONS & TRIGGERS
-- =====================================================

-- 1. updated_at bookkeeping for quotes
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER quotes_updated_at
  BEFORE UPDATE ON quotes
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- 2. Quote number generator — HARDENED
--    • Uses MAX(sequence)+1 so deleted rows don't collide
--    • Serialises inserts to avoid duplicate numbers under load
--    • ALWAYS overrides whatever the client sent — stops junk like
--      UA-2026-326788 from slipping in.
CREATE OR REPLACE FUNCTION generate_quote_number()
RETURNS TRIGGER AS $$
DECLARE
  year_str text;
  next_seq integer;
BEGIN
  year_str := to_char(now(), 'YYYY');

  LOCK TABLE quotes IN SHARE ROW EXCLUSIVE MODE;

  SELECT COALESCE(
           MAX(
             NULLIF(
               regexp_replace(quote_number, '^UA-' || year_str || '-', ''),
               ''
             )::int
           ),
           0
         ) + 1
    INTO next_seq
    FROM quotes
   WHERE quote_number ~ ('^UA-' || year_str || '-[0-9]+$');

  NEW.quote_number := 'UA-' || year_str || '-' || LPAD(next_seq::text, 4, '0');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER quotes_quote_number
  BEFORE INSERT ON quotes
  FOR EACH ROW
  EXECUTE FUNCTION generate_quote_number();

-- 3. Auto-create a follow-up when a quote flips to "sent"
CREATE OR REPLACE FUNCTION auto_create_followup()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.status = 'sent' AND (OLD.status IS NULL OR OLD.status != 'sent') THEN
    INSERT INTO follow_ups (quote_id, assigned_to, follow_up_date, note)
    VALUES (
      NEW.id,
      NEW.created_by,
      (now() + INTERVAL '3 days')::date,
      'Auto follow-up after quote sent'
    );
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER quotes_auto_followup
  AFTER INSERT OR UPDATE OF status ON quotes
  FOR EACH ROW EXECUTE FUNCTION auto_create_followup();

-- 4. When a final payment arrives, credit the sales person's
--    monthly_sales_data for that month
CREATE OR REPLACE FUNCTION handle_final_payment()
RETURNS TRIGGER AS $$
DECLARE
  quote_rec quotes%ROWTYPE;
  month_str text;
  rev_type text;
BEGIN
  IF NEW.is_final_payment = true AND (OLD.is_final_payment IS NULL OR OLD.is_final_payment = false) THEN
    SELECT * INTO quote_rec FROM quotes WHERE id = NEW.quote_id;
    month_str := to_char(NEW.payment_date, 'YYYY-MM');
    rev_type  := quote_rec.revenue_type;

    IF rev_type = 'new' THEN
      INSERT INTO monthly_sales_data (staff_id, month_year, new_client_revenue)
      VALUES (quote_rec.created_by, month_str, quote_rec.subtotal)
      ON CONFLICT (staff_id, month_year)
      DO UPDATE SET
        new_client_revenue = monthly_sales_data.new_client_revenue + quote_rec.subtotal,
        updated_at = now();
    ELSE
      INSERT INTO monthly_sales_data (staff_id, month_year, renewal_revenue)
      VALUES (quote_rec.created_by, month_str, quote_rec.subtotal)
      ON CONFLICT (staff_id, month_year)
      DO UPDATE SET
        renewal_revenue = monthly_sales_data.renewal_revenue + quote_rec.subtotal,
        updated_at = now();
    END IF;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER payments_final_trigger
  AFTER INSERT OR UPDATE OF is_final_payment ON payments
  FOR EACH ROW EXECUTE FUNCTION handle_final_payment();

-- 5. Auto-create a staff_incentive_profile whenever a sales user
--    is added. Admins don't need profiles.
CREATE OR REPLACE FUNCTION auto_create_incentive_profile()
RETURNS TRIGGER AS $$
DECLARE
  s incentive_settings%ROWTYPE;
BEGIN
  IF NEW.role <> 'sales' THEN
    RETURN NEW;
  END IF;

  IF EXISTS (SELECT 1 FROM staff_incentive_profiles WHERE user_id = NEW.id) THEN
    RETURN NEW;
  END IF;

  SELECT * INTO s FROM incentive_settings LIMIT 1;

  INSERT INTO staff_incentive_profiles (
    user_id, monthly_salary, sales_multiplier,
    new_client_rate, renewal_rate, flat_bonus,
    join_date, is_active
  ) VALUES (
    NEW.id, 0,
    COALESCE(s.default_multiplier, 5),
    COALESCE(s.new_client_rate, 0.05),
    COALESCE(s.renewal_rate, 0.02),
    COALESCE(s.default_flat_bonus, 10000),
    CURRENT_DATE, true
  );

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER users_auto_incentive_profile
  AFTER INSERT ON users
  FOR EACH ROW EXECUTE FUNCTION auto_create_incentive_profile();

-- =====================================================
-- ROW LEVEL SECURITY
-- =====================================================

ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE cities ENABLE ROW LEVEL SECURITY;
ALTER TABLE quotes ENABLE ROW LEVEL SECURITY;
ALTER TABLE quote_cities ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE staff_incentive_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE monthly_sales_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE follow_ups ENABLE ROW LEVEL SECURITY;
ALTER TABLE incentive_settings ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION get_my_role()
RETURNS text AS $$
  SELECT role FROM users WHERE id = auth.uid()
$$ LANGUAGE sql SECURITY DEFINER;

-- USERS
CREATE POLICY "users_read_all"    ON users FOR SELECT USING (auth.uid() IS NOT NULL);
CREATE POLICY "users_admin_write" ON users FOR ALL    USING (get_my_role() = 'admin');

-- CITIES
CREATE POLICY "cities_read_all"    ON cities FOR SELECT USING (auth.uid() IS NOT NULL);
CREATE POLICY "cities_admin_write" ON cities FOR ALL    USING (get_my_role() = 'admin');

-- QUOTES
CREATE POLICY "quotes_admin_all"   ON quotes FOR ALL USING (get_my_role() = 'admin');
CREATE POLICY "quotes_sales_own"   ON quotes FOR ALL
  USING (get_my_role() = 'sales' AND created_by = auth.uid());

-- QUOTE_CITIES
CREATE POLICY "qc_admin_all"       ON quote_cities FOR ALL USING (get_my_role() = 'admin');
CREATE POLICY "qc_sales_own"       ON quote_cities FOR ALL
  USING (
    get_my_role() = 'sales' AND
    quote_id IN (SELECT id FROM quotes WHERE created_by = auth.uid())
  );

-- PAYMENTS
CREATE POLICY "payments_admin_all" ON payments FOR ALL USING (get_my_role() = 'admin');
CREATE POLICY "payments_sales_read_own" ON payments FOR SELECT
  USING (
    get_my_role() = 'sales' AND
    quote_id IN (SELECT id FROM quotes WHERE created_by = auth.uid())
  );
-- Allow sales to insert payments on their own quotes
CREATE POLICY "payments_sales_insert_own" ON payments FOR INSERT
  WITH CHECK (
    get_my_role() = 'sales' AND
    quote_id IN (SELECT id FROM quotes WHERE created_by = auth.uid())
  );

-- STAFF INCENTIVE PROFILES
CREATE POLICY "sip_admin_all" ON staff_incentive_profiles FOR ALL USING (get_my_role() = 'admin');
CREATE POLICY "sip_sales_own" ON staff_incentive_profiles FOR SELECT
  USING (get_my_role() = 'sales' AND user_id = auth.uid());

-- MONTHLY SALES DATA
CREATE POLICY "msd_admin_all" ON monthly_sales_data FOR ALL USING (get_my_role() = 'admin');
CREATE POLICY "msd_sales_own" ON monthly_sales_data FOR SELECT
  USING (get_my_role() = 'sales' AND staff_id = auth.uid());

-- FOLLOW UPS
CREATE POLICY "fu_admin_all"  ON follow_ups FOR ALL USING (get_my_role() = 'admin');
CREATE POLICY "fu_sales_own"  ON follow_ups FOR ALL
  USING (get_my_role() = 'sales' AND assigned_to = auth.uid());

-- INCENTIVE SETTINGS
CREATE POLICY "is_admin_all"  ON incentive_settings FOR ALL    USING (get_my_role() = 'admin');
CREATE POLICY "is_sales_read" ON incentive_settings FOR SELECT USING (auth.uid() IS NOT NULL);

-- =====================================================
-- REALTIME — lets the dashboard update live when a payment
-- is recorded on another page / another person's device
-- =====================================================

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    CREATE PUBLICATION supabase_realtime;
  END IF;
END $$;

DO $$
BEGIN
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.payments;            EXCEPTION WHEN duplicate_object THEN NULL; END;
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.quotes;              EXCEPTION WHEN duplicate_object THEN NULL; END;
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.monthly_sales_data;  EXCEPTION WHEN duplicate_object THEN NULL; END;
END $$;

-- =====================================================
-- DONE. Next step is in DEPLOY_GUIDE.md → "Seed admin user".
-- =====================================================

-- ============================================================
-- END: supabase_schema.sql
-- ============================================================

-- ============================================================
-- BEGIN: phase2_additions.sql
-- ============================================================
-- =====================================================
-- UNTITLED ADFLUX — PHASE 2 SCHEMA ADDITIONS (IDEMPOTENT)
-- =====================================================
-- RUN THIS ONCE in your Supabase SQL Editor AFTER Phase 1.
-- This file is ADDITIVE and SAFE TO RE-RUN — it drops and
-- recreates policies/triggers/functions so if you ran an
-- earlier version and got the "policy already exists" error,
-- just run this whole file again.
-- =====================================================

-- =====================================================
-- 1. INCENTIVE PAYOUTS — admin punches actual paid amounts
--    (full or partial) against a staff/month.
-- =====================================================

CREATE TABLE IF NOT EXISTS incentive_payouts (
  id                uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  staff_id          uuid REFERENCES users(id) ON DELETE CASCADE,
  month_year        text NOT NULL,                 -- 'YYYY-MM'
  amount_paid       numeric NOT NULL,
  is_full_payment   boolean DEFAULT false,
  note              text,
  paid_date         date DEFAULT CURRENT_DATE,
  paid_by           uuid REFERENCES users(id),
  created_at        timestamptz DEFAULT now()
);

ALTER TABLE incentive_payouts ENABLE ROW LEVEL SECURITY;

-- Drop first so re-running is safe
DROP POLICY IF EXISTS "ip_admin_all" ON incentive_payouts;
DROP POLICY IF EXISTS "ip_sales_own" ON incentive_payouts;

CREATE POLICY "ip_admin_all" ON incentive_payouts FOR ALL
  USING (get_my_role() = 'admin');

CREATE POLICY "ip_sales_own" ON incentive_payouts FOR SELECT
  USING (get_my_role() = 'sales' AND staff_id = auth.uid());

-- =====================================================
-- 2. PAYMENT POLICIES — sales can now add/edit/delete
--    their OWN non-final payments on their OWN quotes.
-- =====================================================

DROP POLICY IF EXISTS "payments_sales_update_own" ON payments;
DROP POLICY IF EXISTS "payments_sales_delete_own" ON payments;

-- Sales UPDATE: allowed only if the row is currently non-final
-- AND stays non-final AND belongs to the sales user's own quote.
CREATE POLICY "payments_sales_update_own" ON payments FOR UPDATE
  USING (
    get_my_role() = 'sales'
    AND is_final_payment = false
    AND quote_id IN (SELECT id FROM quotes WHERE created_by = auth.uid())
  )
  WITH CHECK (
    get_my_role() = 'sales'
    AND is_final_payment = false
    AND quote_id IN (SELECT id FROM quotes WHERE created_by = auth.uid())
  );

-- Sales DELETE: allowed only if the row is non-final AND belongs
-- to the sales user's own quote.
CREATE POLICY "payments_sales_delete_own" ON payments FOR DELETE
  USING (
    get_my_role() = 'sales'
    AND is_final_payment = false
    AND quote_id IN (SELECT id FROM quotes WHERE created_by = auth.uid())
  );

-- =====================================================
-- 3. FINAL-PAYMENT RECALC — the original trigger only fired on
--    INSERT / UPDATE-to-true. We now also need to REVERSE the
--    monthly_sales_data credit if a final payment is edited or
--    deleted.
-- =====================================================

-- When a final payment is UPDATED (e.g. amount changed, or final
-- flag turned OFF), this function rebuilds monthly_sales_data for
-- that staff+month from scratch. Safer than diffing.
CREATE OR REPLACE FUNCTION rebuild_monthly_sales(p_staff uuid, p_month text)
RETURNS void AS $$
DECLARE
  new_rev numeric := 0;
  ren_rev numeric := 0;
BEGIN
  SELECT
    COALESCE(SUM(CASE WHEN q.revenue_type = 'new' THEN q.subtotal ELSE 0 END), 0),
    COALESCE(SUM(CASE WHEN q.revenue_type = 'renewal' THEN q.subtotal ELSE 0 END), 0)
  INTO new_rev, ren_rev
  FROM payments p
  JOIN quotes q ON q.id = p.quote_id
  WHERE p.is_final_payment = true
    AND q.created_by = p_staff
    AND to_char(p.payment_date, 'YYYY-MM') = p_month;

  INSERT INTO monthly_sales_data (staff_id, month_year, new_client_revenue, renewal_revenue)
  VALUES (p_staff, p_month, new_rev, ren_rev)
  ON CONFLICT (staff_id, month_year)
  DO UPDATE SET
    new_client_revenue = EXCLUDED.new_client_revenue,
    renewal_revenue    = EXCLUDED.renewal_revenue,
    updated_at         = now();
END;
$$ LANGUAGE plpgsql;

-- Handle UPDATE: if the payment's final flag or amount changed,
-- or if it moved between months, rebuild affected month(s).
CREATE OR REPLACE FUNCTION handle_payment_update()
RETURNS TRIGGER AS $$
DECLARE
  old_month text;
  new_month text;
  old_staff uuid;
  new_staff uuid;
BEGIN
  -- Only care about updates that touch the ledger.
  IF OLD.is_final_payment = false AND NEW.is_final_payment = false THEN
    RETURN NEW;
  END IF;

  SELECT created_by INTO old_staff FROM quotes WHERE id = OLD.quote_id;
  SELECT created_by INTO new_staff FROM quotes WHERE id = NEW.quote_id;

  old_month := to_char(OLD.payment_date, 'YYYY-MM');
  new_month := to_char(NEW.payment_date, 'YYYY-MM');

  -- Rebuild old side (covers: flag was true and is now false, or
  -- date moved to a different month, or quote assignment changed)
  IF OLD.is_final_payment = true THEN
    PERFORM rebuild_monthly_sales(old_staff, old_month);
  END IF;

  -- Rebuild new side (covers: flag just became true, or still true
  -- with changed amount/date/quote)
  IF NEW.is_final_payment = true
     AND (old_staff <> new_staff OR old_month <> new_month OR NOT (OLD.is_final_payment = true)) THEN
    PERFORM rebuild_monthly_sales(new_staff, new_month);
  ELSIF NEW.is_final_payment = true THEN
    -- same staff, same month, stayed-final — rebuild once to catch
    -- amount changes reflected via the quote's subtotal
    PERFORM rebuild_monthly_sales(new_staff, new_month);
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS payments_update_recalc ON payments;
CREATE TRIGGER payments_update_recalc
  AFTER UPDATE ON payments
  FOR EACH ROW EXECUTE FUNCTION handle_payment_update();

-- Handle DELETE: if a final payment is removed, rebuild its month.
CREATE OR REPLACE FUNCTION handle_payment_delete()
RETURNS TRIGGER AS $$
DECLARE
  staff_uid uuid;
  month_str text;
BEGIN
  IF OLD.is_final_payment = true THEN
    SELECT created_by INTO staff_uid FROM quotes WHERE id = OLD.quote_id;
    month_str := to_char(OLD.payment_date, 'YYYY-MM');
    PERFORM rebuild_monthly_sales(staff_uid, month_str);
  END IF;
  RETURN OLD;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS payments_delete_recalc ON payments;
CREATE TRIGGER payments_delete_recalc
  AFTER DELETE ON payments
  FOR EACH ROW EXECUTE FUNCTION handle_payment_delete();

-- =====================================================
-- 4. REALTIME — add incentive_payouts so the dashboard
--    reflects paid-out incentive live.
-- =====================================================

DO $$
BEGIN
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.incentive_payouts;
        EXCEPTION WHEN duplicate_object THEN NULL; END;
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.follow_ups;
        EXCEPTION WHEN duplicate_object THEN NULL; END;
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.quote_cities;
        EXCEPTION WHEN duplicate_object THEN NULL; END;
END $$;

-- =====================================================
-- DONE. No data was changed. Safe to re-run this whole
-- file again if anything errors next time.
-- =====================================================

-- ============================================================
-- END: phase2_additions.sql
-- ============================================================

-- ============================================================
-- BEGIN: supabase_quote_number_fix.sql
-- ============================================================
-- =========================================================================
-- Adflux — Quote number generator fix (race-free via SEQUENCE)
-- =========================================================================
-- WHAT WAS WRONG:
--   The old generate_quote_number() trigger did SELECT MAX(...) + 1.
--   Under concurrent inserts, two sessions could both read MAX = N and
--   both try to insert N+1 → one fails with a duplicate-key error.
--
-- WHAT WE DO NOW:
--   Use a Postgres SEQUENCE. nextval() is atomic — each call returns a
--   unique number, even if two sessions call it in the same millisecond.
--   Format stays the same: UA-YYYY-####   (YYYY = current year)
--
--   NOTE: numbers no longer reset to 0001 on Jan 1. The counter keeps
--   climbing across years, e.g. UA-2026-0312 → UA-2027-0313. This is
--   the cost of going race-free with a single sequence, and for an
--   internal tool it's a fair trade: numbers stay globally unique and
--   monotonically increasing forever, which is actually cleaner for
--   audit / filing / search.
--
-- SAFE TO RUN ON LIVE:
--   - Idempotent (CREATE SEQUENCE IF NOT EXISTS, CREATE OR REPLACE FUNCTION)
--   - Sequence is seeded to the current MAX suffix across ALL existing
--     quotes, so the next quote created is MAX+1 — no collisions with
--     existing rows.
--   - Trigger name quotes_quote_number stays the same; only the function
--     body changes.
-- =========================================================================

-- 1) Create the sequence (once, idempotent)
CREATE SEQUENCE IF NOT EXISTS public.quote_number_seq
  START WITH 1
  INCREMENT BY 1
  NO MINVALUE
  NO MAXVALUE
  CACHE 1;

-- 2) Seed the sequence to the max numeric suffix across all existing
--    quotes, so the next nextval() call returns a number that doesn't
--    already exist on any row.
--
--    Works for any row whose quote_number matches 'UA-####-####...' —
--    the last dash-delimited segment is cast to int and we take the max.
SELECT setval(
  'public.quote_number_seq',
  GREATEST(
    COALESCE((
      SELECT MAX(
        CAST(
          regexp_replace(quote_number, '^.*-', '') AS INTEGER
        )
      )
      FROM public.quotes
      WHERE quote_number ~ '^UA-\d{4}-\d+$'
    ), 0),
    1   -- never let setval go below 1
  ),
  true  -- is_called = true → next nextval() returns this + 1
);

-- 3) Replace the trigger function. The trigger itself (quotes_quote_number,
--    BEFORE INSERT on quotes) already points at this function by name, so
--    we don't need to drop/recreate the trigger.
CREATE OR REPLACE FUNCTION public.generate_quote_number()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Always stamp a fresh server-side number; ignore whatever the client sent.
  NEW.quote_number :=
    'UA-'
    || TO_CHAR(CURRENT_DATE, 'YYYY')
    || '-'
    || LPAD(nextval('public.quote_number_seq')::text, 4, '0');
  RETURN NEW;
END;
$$;

-- 4) Sanity check (optional — safe to run, just shows current state).
--    Uncomment to view in SQL editor:
-- SELECT last_value, is_called FROM public.quote_number_seq;
-- SELECT MAX(quote_number) FROM public.quotes;

-- ============================================================
-- END: supabase_quote_number_fix.sql
-- ============================================================

-- ============================================================
-- BEGIN: supabase_storage_quote_pdfs.sql
-- ============================================================
-- =======================================================================
-- Storage bucket: quote-pdfs
-- =======================================================================
-- Purpose
--   Public bucket that holds the generated quotation PDFs so they can be
--   shared as a URL inside WhatsApp messages. WhatsApp click-to-chat
--   (wa.me) URLs only carry plaintext — they cannot attach files —
--   so the PDF has to live at a publicly reachable URL.
--
--   Upload path convention (enforced by the client, not SQL):
--     quote-pdfs/{quote_number}/{timestamp}.pdf
--   The timestamp means regenerating a PDF produces a new object rather
--   than overwriting the old one, so WhatsApp recipients never hit a
--   stale cache.
--
-- How to apply
--   Run this entire file in Supabase SQL Editor once. It is idempotent —
--   safe to re-run. No existing PDFs will be touched.
--
-- Security posture
--   Reads: public (anyone with the URL can open the PDF — same as if
--          you emailed it as an attachment).
--   Writes: authenticated users only. That covers every staff member
--          logged into the Adflux app. Anonymous web visitors cannot
--          upload.
-- =======================================================================

-- 1) Create the bucket (public read)
insert into storage.buckets (id, name, public)
values ('quote-pdfs', 'quote-pdfs', true)
on conflict (id) do update
  set public = excluded.public;

-- 2) RLS policies on storage.objects scoped to this bucket
--    (RLS is already enabled on storage.objects by Supabase defaults.)

-- Public read — anyone with the URL can download.
drop policy if exists "quote-pdfs: public read" on storage.objects;
create policy "quote-pdfs: public read"
  on storage.objects
  for select
  using ( bucket_id = 'quote-pdfs' );

-- Authenticated upload — any logged-in staff member can upload.
drop policy if exists "quote-pdfs: authenticated insert" on storage.objects;
create policy "quote-pdfs: authenticated insert"
  on storage.objects
  for insert
  to authenticated
  with check ( bucket_id = 'quote-pdfs' );

-- Authenticated update (upsert safety net — only fires when the client
-- passes upsert:true, which we currently don't, but keeping this policy
-- here means a future code change won't silently 403).
drop policy if exists "quote-pdfs: authenticated update" on storage.objects;
create policy "quote-pdfs: authenticated update"
  on storage.objects
  for update
  to authenticated
  using ( bucket_id = 'quote-pdfs' )
  with check ( bucket_id = 'quote-pdfs' );

-- Authenticated delete — lets an admin prune old PDFs through the
-- Supabase console or a future cleanup script. We do NOT expose delete
-- in the app UI right now.
drop policy if exists "quote-pdfs: authenticated delete" on storage.objects;
create policy "quote-pdfs: authenticated delete"
  on storage.objects
  for delete
  to authenticated
  using ( bucket_id = 'quote-pdfs' );

-- ============================================================
-- END: supabase_storage_quote_pdfs.sql
-- ============================================================

-- ============================================================
-- BEGIN: supabase_gst_rate.sql
-- ============================================================
-- GST rate per quote
--
-- Before: every quote was taxed at a hardcoded 18% in the app layer.
-- After:  each quote stores its own rate. UI offers "GST 18%" or "No GST"
--         (0.00). The column is NUMERIC rather than BOOLEAN so you can add
--         12% / 5% later without another migration.
--
-- Default 0.18 means every existing quote is treated as 18% GST, which
-- matches how they were calculated at the time — no backfill pass needed.

ALTER TABLE quotes
  ADD COLUMN IF NOT EXISTS gst_rate NUMERIC(5,4) NOT NULL DEFAULT 0.18;

COMMENT ON COLUMN quotes.gst_rate IS
  'GST rate applied to this quote. 0.18 = 18%, 0 = No GST.';

-- ============================================================
-- END: supabase_gst_rate.sql
-- ============================================================

-- ============================================================
-- BEGIN: supabase_clients_module.sql
-- ============================================================
-- =====================================================
-- UNTITLED ADFLUX — CLIENTS MODULE (migration)
-- =====================================================
--
-- Adds a `clients` table that sits alongside `quotes`. Each quote still
-- carries its own denormalized client_* fields (name, phone, etc.) as a
-- historical snapshot — editing a client here does NOT rewrite past
-- quotes. Think of this table as the CRM view; quotes are the ledger.
--
-- Dedup key: (phone, created_by). Each salesperson gets their own
-- client list, so two reps talking to the same number keep separate
-- rows (prevents silent lead-stealing). Admin sees the whole set.
--
-- The app auto-upserts a row here whenever a quote is saved (see
-- src/hooks/useQuotes.js). This file also includes a one-time backfill
-- from the existing quotes table at the end.
--
-- Run in Supabase SQL Editor, top to bottom. Idempotent — can be run
-- again on a database that already has a partial clients table; each
-- statement guards with IF NOT EXISTS.
-- =====================================================

-- ──────────────────────────────────────────────────────
-- 1. Table
-- ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS clients (
  id                 uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  name               text NOT NULL,
  company            text,
  phone              text NOT NULL,
  email              text,
  gstin              text,
  address            text,
  notes              text,

  -- Owner — the sales rep who created the first quote for this client.
  -- RLS is keyed off this. NULL means "admin-created" (e.g. direct from
  -- the clients page) — those rows are visible to admins only.
  created_by         uuid REFERENCES users(id) ON DELETE SET NULL,

  -- Activity snapshot maintained by the app on each quote save.
  -- Denormalized so the clients list can render fast without joining
  -- quotes every render.
  first_quote_at     timestamptz,
  last_quote_at      timestamptz,
  quote_count        integer DEFAULT 0,
  total_won_amount   numeric DEFAULT 0,

  created_at         timestamptz DEFAULT now(),
  updated_at         timestamptz DEFAULT now()
);

-- One row per (phone, owner). Two sales reps can each have their own
-- record for the same phone. Admin-created rows (created_by IS NULL)
-- also dedupe on phone — only one unassigned record per number.
CREATE UNIQUE INDEX IF NOT EXISTS clients_phone_owner_uk
  ON clients (phone, COALESCE(created_by::text, ''));

-- Helper indexes — search hits name/company a lot, and the list view
-- orders by last_quote_at DESC.
CREATE INDEX IF NOT EXISTS clients_name_idx         ON clients (lower(name));
CREATE INDEX IF NOT EXISTS clients_company_idx      ON clients (lower(company));
CREATE INDEX IF NOT EXISTS clients_last_quote_idx   ON clients (last_quote_at DESC NULLS LAST);
CREATE INDEX IF NOT EXISTS clients_created_by_idx   ON clients (created_by);

-- ──────────────────────────────────────────────────────
-- 2. updated_at trigger
-- ──────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION clients_touch_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS clients_touch_updated_at_trg ON clients;
CREATE TRIGGER clients_touch_updated_at_trg
  BEFORE UPDATE ON clients
  FOR EACH ROW EXECUTE FUNCTION clients_touch_updated_at();

-- ──────────────────────────────────────────────────────
-- 3. Row-level security
--   • Admin  → full access to every row
--   • Sales  → SELECT / UPDATE / INSERT rows they own (created_by = self)
--   • Nobody deletes through the API (handled by admin in SQL if ever
--     needed; clients are rarely truly deleted).
-- ──────────────────────────────────────────────────────
ALTER TABLE clients ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "clients_admin_all"        ON clients;
DROP POLICY IF EXISTS "clients_sales_select_own" ON clients;
DROP POLICY IF EXISTS "clients_sales_insert_own" ON clients;
DROP POLICY IF EXISTS "clients_sales_update_own" ON clients;

CREATE POLICY "clients_admin_all" ON clients
  FOR ALL USING (get_my_role() = 'admin');

CREATE POLICY "clients_sales_select_own" ON clients
  FOR SELECT USING (get_my_role() = 'sales' AND created_by = auth.uid());

CREATE POLICY "clients_sales_insert_own" ON clients
  FOR INSERT WITH CHECK (get_my_role() = 'sales' AND created_by = auth.uid());

CREATE POLICY "clients_sales_update_own" ON clients
  FOR UPDATE USING (get_my_role() = 'sales' AND created_by = auth.uid());

-- ──────────────────────────────────────────────────────
-- 4. Realtime — dashboard + clients list both subscribe
-- ──────────────────────────────────────────────────────
ALTER PUBLICATION supabase_realtime ADD TABLE clients;

-- ──────────────────────────────────────────────────────
-- 5. Backfill from existing quotes
--
-- For every unique (client_phone, created_by) in quotes, insert a
-- clients row with the latest name/company/etc. "Latest" is picked by
-- row_number() ordered by quote updated_at DESC so the most recently
-- worked quote wins. Aggregates (first_quote_at, last_quote_at,
-- quote_count, total_won_amount) are computed alongside.
--
-- ON CONFLICT DO NOTHING — safe to re-run; won't overwrite a clients
-- row you've already edited by hand.
-- ──────────────────────────────────────────────────────
WITH ranked AS (
  SELECT
    q.*,
    row_number() OVER (
      PARTITION BY q.client_phone, q.created_by
      ORDER BY COALESCE(q.updated_at, q.created_at) DESC
    ) AS rn
  FROM quotes q
  WHERE q.client_phone IS NOT NULL AND length(trim(q.client_phone)) > 0
),
latest AS (
  SELECT * FROM ranked WHERE rn = 1
),
aggs AS (
  SELECT
    client_phone,
    created_by,
    MIN(created_at)                                      AS first_quote_at,
    MAX(COALESCE(updated_at, created_at))                AS last_quote_at,
    COUNT(*)                                             AS quote_count,
    COALESCE(SUM(CASE WHEN status = 'won' THEN total_amount ELSE 0 END), 0) AS total_won
  FROM quotes
  WHERE client_phone IS NOT NULL AND length(trim(client_phone)) > 0
  GROUP BY client_phone, created_by
)
INSERT INTO clients (
  name, company, phone, email, gstin, address, notes,
  created_by, first_quote_at, last_quote_at, quote_count, total_won_amount
)
SELECT
  COALESCE(NULLIF(trim(l.client_name), ''), 'Unknown'),
  NULLIF(trim(l.client_company), ''),
  trim(l.client_phone),
  NULLIF(trim(l.client_email), ''),
  NULLIF(trim(l.client_gst), ''),
  NULLIF(trim(l.client_address), ''),
  NULLIF(trim(l.client_notes), ''),
  l.created_by,
  a.first_quote_at,
  a.last_quote_at,
  a.quote_count,
  a.total_won
FROM latest l
JOIN aggs a
  ON a.client_phone = l.client_phone
 AND a.created_by IS NOT DISTINCT FROM l.created_by
ON CONFLICT (phone, COALESCE(created_by::text, '')) DO NOTHING;

-- =====================================================
-- Done. Verify with:
--   SELECT count(*) FROM clients;
--   SELECT name, phone, quote_count, total_won_amount
--   FROM clients ORDER BY last_quote_at DESC LIMIT 10;
-- =====================================================

-- ============================================================
-- END: supabase_clients_module.sql
-- ============================================================

-- ============================================================
-- BEGIN: supabase_slot_metadata.sql
-- ============================================================
-- Slot metadata on quote_cities
--
-- Adds ad-spot metadata to each quote line. These are PURE METADATA —
-- they do not affect pricing. Pricing is driven solely by the rep-
-- negotiated offered_rate × screens × duration_months (see
-- src/components/quotes/QuoteWizard/Step2Campaign.jsx::calcTotal).
--
-- Fields:
--   slot_seconds          Length of each ad spot, in seconds. Rep picks
--                         from 10 / 15 / 20 / 30. The PDF previously
--                         hardcoded "10 SEC" — once this column is in
--                         place the PDF can render the real value.
--   slots_per_day         Promised daily spot count per screen. Default
--                         100. Reps can negotiate this up (premium
--                         placement) or down (low-traffic board).
--   slots_override_reason Free-text reason, required by the UI when
--                         slots_per_day is not 100. Mirrors the
--                         override_reason column that already tracks
--                         rate overrides.
--
-- Defaults match the pre-migration implicit assumption (10s ads, 100
-- slots/day) so old rows keep their meaning when the UI falls back to
-- defaults while rendering them.

ALTER TABLE quote_cities
  ADD COLUMN IF NOT EXISTS slot_seconds          INTEGER     NOT NULL DEFAULT 10,
  ADD COLUMN IF NOT EXISTS slots_per_day         INTEGER     NOT NULL DEFAULT 100,
  ADD COLUMN IF NOT EXISTS slots_override_reason TEXT;

-- Keep the defaults sane even if someone writes a raw INSERT without
-- specifying. 1 second / 1 slot would both be nonsensical for a real
-- campaign but they unblock data insertion and the UI clamps on edit.
ALTER TABLE quote_cities
  ADD CONSTRAINT quote_cities_slot_seconds_positive  CHECK (slot_seconds  > 0),
  ADD CONSTRAINT quote_cities_slots_per_day_positive CHECK (slots_per_day > 0);

COMMENT ON COLUMN quote_cities.slot_seconds IS
  'Ad spot length in seconds (10/15/20/30). Metadata only — does NOT factor into campaign_total.';
COMMENT ON COLUMN quote_cities.slots_per_day IS
  'Promised ad plays per screen per day. Default 100; deviations require slots_override_reason.';
COMMENT ON COLUMN quote_cities.slots_override_reason IS
  'Why slots_per_day differs from the default of 100. NULL when at default.';

-- ============================================================
-- END: supabase_slot_metadata.sql
-- ============================================================

-- ============================================================
-- BEGIN: supabase_hr_module.sql
-- ============================================================
-- =======================================================================
-- HR MODULE — Offer letters for pre-hire sales candidates
-- =======================================================================
--
-- What this adds
--   1. hr_offer_templates  — Phase 2 editable boilerplate. For Phase 1
--                            we seed ONE default row with hardcoded
--                            clause text; the UI doesn't expose editing
--                            yet.
--   2. hr_offers           — one row per candidate. Tracks the whole
--                            pre-hire lifecycle:
--                              draft → sent → filled → accepted → converted_to_user
--                            Admin fills the top block at "Send Offer"
--                            time. Candidate fills personal details via
--                            a public invite-token link (no auth).
--                            On acceptance, the generated PDF URL is
--                            stored in offer_pdf_url.
--   3. Two SECURITY DEFINER RPCs for anonymous candidate access:
--        fetch_offer_by_token(token)      — read-only summary for the
--                                           form page
--        submit_offer_acceptance(token, <personal fields>, pdf_url)
--                                         — one-shot upsert that writes
--                                           personal details + PDF URL
--                                           + flips status to 'accepted'
--      These are the ONLY paths open to anon. The table itself stays
--      admin-only under standard RLS. This keeps the attack surface to
--      two whitelisted functions instead of a "read-if-you-guess-the-
--      token" blanket policy.
--   4. offer-letters storage bucket (public read, authenticated write
--      for admin uploads; candidate-side uploads go through a Supabase
--      Storage signed-URL flow initiated by the admin, NOT here).
--
-- What this DOES NOT touch
--   - No ALTER on users, quotes, cities, or any existing table.
--   - No ALTER on auth schema.
--   - User creation at "Convert to User" time happens via the existing
--     supabaseSignup flow (client-side) — this migration only stores
--     the resulting user_id in hr_offers.converted_user_id.
--
-- How to apply
--   Run this entire file ONCE in the Supabase SQL Editor. Idempotent —
--   safe to re-run; every DROP/CREATE is guarded.
-- =======================================================================

-- =====================================================================
-- 1. TEMPLATES — Phase 2 editable. Phase 1 uses ONE default row.
-- =====================================================================

CREATE TABLE IF NOT EXISTS hr_offer_templates (
  id                  uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  name                text NOT NULL,
  -- Boilerplate blocks. Plain text (optionally with {{placeholders}}
  -- merged client-side at PDF time). Phase 1 values are the ones from
  -- the Jignesh Brahmbhatt letter — 6-month probation, 15/30-day
  -- notice, ₹12-15L target, 6+6 leave, 12-month non-compete, etc.
  probation_months    integer DEFAULT 6,
  notice_probation_days integer DEFAULT 15,
  notice_confirmed_days integer DEFAULT 30,
  min_monthly_target  numeric DEFAULT 100000,
  paid_leave_days     integer DEFAULT 6,
  sick_leave_days     integer DEFAULT 6,
  non_compete_months  integer DEFAULT 12,
  working_days        text   DEFAULT 'Monday to Saturday',
  travel_percent      text   DEFAULT '50-60%',
  place_default       text   DEFAULT 'Vadodara',
  -- Long-form clause bodies. Stored on the template so Phase 2 can
  -- edit them without a code change. Defaults below mirror the
  -- sample letter the user shared.
  confidentiality_text text,
  termination_text     text,
  company_assets_text  text,
  remuneration_text    text,
  is_default          boolean DEFAULT false,
  is_active           boolean DEFAULT true,
  created_at          timestamptz DEFAULT now(),
  updated_at          timestamptz DEFAULT now()
);

-- Seed the Phase 1 default. INSERT only if no default exists yet — so
-- this migration can re-run without duplicating the row.
INSERT INTO hr_offer_templates (
  name, is_default,
  confidentiality_text, termination_text,
  company_assets_text, remuneration_text
)
SELECT
  'Sales Person — Default',
  true,
  'You shall, during the period of your employment or at any time '
  || 'thereafter, not disclose or use any confidential information '
  || 'relating to the business of the Company for your own benefit '
  || 'or for the benefit of any third party.',
  'Either party may terminate this agreement by serving the notice '
  || 'period specified above. The Company reserves the right to '
  || 'terminate immediately in case of misconduct, breach of '
  || 'confidentiality, or material non-performance.',
  'All company assets (laptop, SIM, marketing collateral, client '
  || 'contacts, etc.) issued to you must be returned in good '
  || 'condition on your last working day. Failure to return assets '
  || 'may result in deduction from final settlement.',
  'The remuneration details in this letter are strictly '
  || 'confidential and shall not be disclosed to any third party, '
  || 'including colleagues, under any circumstances.'
WHERE NOT EXISTS (
  SELECT 1 FROM hr_offer_templates WHERE is_default = true
);

-- =====================================================================
-- 2. OFFERS — main table
-- =====================================================================

CREATE TABLE IF NOT EXISTS hr_offers (
  id                        uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  -- Public-facing token the candidate uses to open the form URL.
  -- UUID so enumeration is infeasible; unique so the URL maps to
  -- exactly one offer.
  invite_token              uuid UNIQUE NOT NULL DEFAULT uuid_generate_v4(),

  -- Lifecycle. draft → sent → filled → accepted → converted_to_user.
  -- 'sent' is set the moment the admin copies/shares the link so the
  -- list view can show outstanding invites.
  status                    text NOT NULL DEFAULT 'draft'
                              CHECK (status IN ('draft','sent','filled','accepted','converted_to_user','cancelled')),

  -- --- Admin-filled at Send Offer time -------------------------------
  candidate_name            text NOT NULL,
  candidate_email           text NOT NULL,
  position                  text NOT NULL DEFAULT 'Sales Person',
  territory                 text,
  joining_date              date,
  fixed_salary_monthly      numeric NOT NULL,
  -- Free-form string kept for legacy/Phase 1 offers. New offers use
  -- the structured incentive columns below; the PDF renders the
  -- structured block and ignores this when any of the structured
  -- columns are non-null.
  incentive_text            text,
  -- Structured incentive config — mirrors staff_incentive_profiles
  -- exactly so Convert-to-User can copy these straight into the new
  -- user's profile without mapping. Defaults match the existing Team
  -- modal defaults (5× multiplier, 5% / 2% rates, ₹10k bonus).
  incentive_sales_multiplier numeric DEFAULT 5,
  incentive_new_client_rate  numeric DEFAULT 0.05,
  incentive_renewal_rate     numeric DEFAULT 0.02,
  incentive_flat_bonus       numeric DEFAULT 10000,
  place                     text DEFAULT 'Vadodara',
  template_id               uuid REFERENCES hr_offer_templates(id),

  -- --- Candidate-filled via public form ------------------------------
  full_legal_name           text,
  fathers_name              text,
  dob                       date,
  mobile                    text,
  personal_email            text,
  address_line1             text,
  address_line2             text,
  city                      text,
  district                  text,
  state                     text,
  pincode                   text,
  pan_number                text,
  aadhaar_number            text,
  qualification             text,
  bank_account_number       text,
  bank_name                 text,
  bank_ifsc                 text,
  emergency_contact_name    text,
  emergency_contact_phone   text,
  emergency_contact_rel     text,

  -- --- Acceptance ---------------------------------------------------
  accepted_terms_at         timestamptz,
  accepted_ip               text,
  offer_pdf_url             text,

  -- --- Conversion ---------------------------------------------------
  converted_user_id         uuid REFERENCES users(id),
  converted_at              timestamptz,

  -- --- Bookkeeping --------------------------------------------------
  created_by                uuid REFERENCES users(id),
  created_at                timestamptz DEFAULT now(),
  updated_at                timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS hr_offers_status_idx       ON hr_offers(status);
CREATE INDEX IF NOT EXISTS hr_offers_created_by_idx   ON hr_offers(created_by);
CREATE INDEX IF NOT EXISTS hr_offers_converted_idx    ON hr_offers(converted_user_id);

-- Idempotent ALTERs for already-deployed DBs. Safe no-ops on fresh
-- installs because the columns are already in the CREATE above.
ALTER TABLE hr_offers ADD COLUMN IF NOT EXISTS incentive_sales_multiplier numeric DEFAULT 5;
ALTER TABLE hr_offers ADD COLUMN IF NOT EXISTS incentive_new_client_rate  numeric DEFAULT 0.05;
ALTER TABLE hr_offers ADD COLUMN IF NOT EXISTS incentive_renewal_rate     numeric DEFAULT 0.02;
ALTER TABLE hr_offers ADD COLUMN IF NOT EXISTS incentive_flat_bonus       numeric DEFAULT 10000;

-- updated_at bookkeeping
DROP TRIGGER IF EXISTS hr_offers_updated_at ON hr_offers;
CREATE TRIGGER hr_offers_updated_at
  BEFORE UPDATE ON hr_offers
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

DROP TRIGGER IF EXISTS hr_offer_templates_updated_at ON hr_offer_templates;
CREATE TRIGGER hr_offer_templates_updated_at
  BEFORE UPDATE ON hr_offer_templates
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =====================================================================
-- 3. ROW LEVEL SECURITY
-- =====================================================================

ALTER TABLE hr_offer_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE hr_offers          ENABLE ROW LEVEL SECURITY;

-- Templates: admins read/write; sales read (so salesperson UI can show
-- the template used for their own letter).
DROP POLICY IF EXISTS "hr_templates_admin_all"   ON hr_offer_templates;
DROP POLICY IF EXISTS "hr_templates_sales_read"  ON hr_offer_templates;
CREATE POLICY "hr_templates_admin_all"   ON hr_offer_templates FOR ALL
  USING (get_my_role() = 'admin');
CREATE POLICY "hr_templates_sales_read"  ON hr_offer_templates FOR SELECT
  USING (auth.uid() IS NOT NULL);

-- Offers:
--   - admin: full access
--   - sales: read ONLY their own converted offer (the one that created
--            their user row). Other offers are invisible to them.
--   - anonymous / candidate: NO direct access. The candidate can only
--            reach their own row through the RPC functions below.
DROP POLICY IF EXISTS "hr_offers_admin_all"       ON hr_offers;
DROP POLICY IF EXISTS "hr_offers_sales_own"       ON hr_offers;
CREATE POLICY "hr_offers_admin_all" ON hr_offers FOR ALL
  USING (get_my_role() = 'admin');
CREATE POLICY "hr_offers_sales_own" ON hr_offers FOR SELECT
  USING (get_my_role() = 'sales' AND converted_user_id = auth.uid());

-- =====================================================================
-- 4. PUBLIC RPCs for candidate access
-- =====================================================================
--
-- The candidate is NOT an authenticated user. These functions are the
-- only surface exposed to anon. Both are SECURITY DEFINER so they can
-- bypass RLS with controlled, narrow logic.
--
-- Security notes
--   - The token is required on every call. No listing, no enumeration.
--   - fetch_offer_by_token returns only the public-safe subset of
--     columns — we never leak admin notes, other offers, or
--     conversion metadata.
--   - submit_offer_acceptance rejects any offer that is already
--     'accepted' or 'converted_to_user', so a leaked token can't be
--     used to rewrite an accepted letter.
-- =====================================================================

-- Read-only summary for the public form page.
--
-- DROP before CREATE because Postgres refuses to re-create a function
-- with a different RETURNS TABLE signature via CREATE OR REPLACE
-- (error 42P13). We're adding the 4 structured-incentive columns to
-- the return shape in this migration, so the drop is required once.
DROP FUNCTION IF EXISTS fetch_offer_by_token(uuid);
CREATE OR REPLACE FUNCTION fetch_offer_by_token(p_token uuid)
RETURNS TABLE (
  id                    uuid,
  status                text,
  candidate_name        text,
  candidate_email       text,
  "position"            text,
  territory             text,
  joining_date          date,
  fixed_salary_monthly  numeric,
  incentive_text        text,
  incentive_sales_multiplier numeric,
  incentive_new_client_rate  numeric,
  incentive_renewal_rate     numeric,
  incentive_flat_bonus       numeric,
  place                 text,
  template_id           uuid,
  offer_pdf_url         text,
  accepted_terms_at     timestamptz,
  -- Personal fields — returned so that if a candidate reopens the
  -- link after a partial save we can pre-fill. Empty for fresh
  -- offers.
  full_legal_name           text,
  fathers_name              text,
  dob                       date,
  mobile                    text,
  personal_email            text,
  address_line1             text,
  address_line2             text,
  city                      text,
  district                  text,
  state                     text,
  pincode                   text,
  pan_number                text,
  aadhaar_number            text,
  qualification             text,
  bank_account_number       text,
  bank_name                 text,
  bank_ifsc                 text,
  emergency_contact_name    text,
  emergency_contact_phone   text,
  emergency_contact_rel     text
)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    id, status, candidate_name, candidate_email, "position", territory,
    joining_date, fixed_salary_monthly, incentive_text,
    incentive_sales_multiplier, incentive_new_client_rate,
    incentive_renewal_rate, incentive_flat_bonus,
    place, template_id, offer_pdf_url, accepted_terms_at,
    full_legal_name, fathers_name, dob, mobile, personal_email,
    address_line1, address_line2, city, district, state, pincode,
    pan_number, aadhaar_number, qualification,
    bank_account_number, bank_name, bank_ifsc,
    emergency_contact_name, emergency_contact_phone, emergency_contact_rel
  FROM hr_offers
  WHERE invite_token = p_token
    AND status <> 'cancelled'
  LIMIT 1;
$$;

GRANT EXECUTE ON FUNCTION fetch_offer_by_token(uuid) TO anon, authenticated;

-- One-shot submission: writes candidate-filled fields + the uploaded
-- PDF URL, flips status to 'accepted'. The client is responsible for
-- generating and uploading the PDF FIRST and then passing the URL
-- here — that keeps the function logic trivial and avoids giving anon
-- write access to Storage policies beyond what's already needed.
CREATE OR REPLACE FUNCTION submit_offer_acceptance(
  p_token                    uuid,
  p_full_legal_name          text,
  p_fathers_name             text,
  p_dob                      date,
  p_mobile                   text,
  p_personal_email           text,
  p_address_line1            text,
  p_address_line2            text,
  p_city                     text,
  p_district                 text,
  p_state                    text,
  p_pincode                  text,
  p_pan_number               text,
  p_aadhaar_number           text,
  p_qualification            text,
  p_bank_account_number      text,
  p_bank_name                text,
  p_bank_ifsc                text,
  p_emergency_contact_name   text,
  p_emergency_contact_phone  text,
  p_emergency_contact_rel    text,
  p_offer_pdf_url            text
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_offer_id uuid;
  v_status   text;
BEGIN
  SELECT id, status INTO v_offer_id, v_status
    FROM hr_offers
   WHERE invite_token = p_token
   LIMIT 1;

  IF v_offer_id IS NULL THEN
    RAISE EXCEPTION 'Invalid or expired offer link';
  END IF;

  -- A leaked token must not be able to rewrite an accepted letter.
  IF v_status IN ('accepted','converted_to_user','cancelled') THEN
    RAISE EXCEPTION 'This offer has already been submitted or is no longer active';
  END IF;

  UPDATE hr_offers SET
    full_legal_name         = p_full_legal_name,
    fathers_name            = p_fathers_name,
    dob                     = p_dob,
    mobile                  = p_mobile,
    personal_email          = p_personal_email,
    address_line1           = p_address_line1,
    address_line2           = p_address_line2,
    city                    = p_city,
    district                = p_district,
    state                   = p_state,
    pincode                 = p_pincode,
    pan_number              = p_pan_number,
    aadhaar_number          = p_aadhaar_number,
    qualification           = p_qualification,
    bank_account_number     = p_bank_account_number,
    bank_name               = p_bank_name,
    bank_ifsc               = p_bank_ifsc,
    emergency_contact_name  = p_emergency_contact_name,
    emergency_contact_phone = p_emergency_contact_phone,
    emergency_contact_rel   = p_emergency_contact_rel,
    offer_pdf_url           = p_offer_pdf_url,
    accepted_terms_at       = now(),
    status                  = 'accepted'
  WHERE id = v_offer_id;

  RETURN v_offer_id;
END;
$$;

GRANT EXECUTE ON FUNCTION submit_offer_acceptance(
  uuid, text, text, date, text, text, text, text, text, text, text, text,
  text, text, text, text, text, text, text, text, text, text
) TO anon, authenticated;

-- =====================================================================
-- 5. STORAGE BUCKET — offer-letters
-- =====================================================================
--
-- Public read (admin + salesperson can open the PDF from the app;
-- candidate gets the URL back from submit_offer_acceptance and can
-- bookmark it). Writes allowed for anon AND authenticated, BUT scoped
-- tightly by path prefix:
--   offer-letters/{invite_token}/{timestamp}.pdf
-- So a hostile uploader can overwrite only PDFs for a token they
-- already know — the same secret that grants access to the form.
-- =====================================================================

INSERT INTO storage.buckets (id, name, public)
VALUES ('offer-letters', 'offer-letters', true)
ON CONFLICT (id) DO UPDATE SET public = EXCLUDED.public;

-- Public read
DROP POLICY IF EXISTS "offer-letters: public read" ON storage.objects;
CREATE POLICY "offer-letters: public read"
  ON storage.objects
  FOR SELECT
  USING (bucket_id = 'offer-letters');

-- Anon + authenticated insert. Candidate is anon when uploading the
-- generated PDF from the public form page.
DROP POLICY IF EXISTS "offer-letters: any insert" ON storage.objects;
CREATE POLICY "offer-letters: any insert"
  ON storage.objects
  FOR INSERT
  WITH CHECK (bucket_id = 'offer-letters');

-- Authenticated-only delete (admin cleanup via Supabase console).
DROP POLICY IF EXISTS "offer-letters: authenticated delete" ON storage.objects;
CREATE POLICY "offer-letters: authenticated delete"
  ON storage.objects
  FOR DELETE
  TO authenticated
  USING (bucket_id = 'offer-letters');

-- =====================================================================
-- 6. REALTIME (optional — lets the admin HR list refresh when a
-- candidate submits the form from another device)
-- =====================================================================

DO $$
BEGIN
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.hr_offers;
  EXCEPTION WHEN duplicate_object THEN NULL; END;
END $$;

-- =====================================================================
-- DONE.
-- =====================================================================

-- ============================================================
-- END: supabase_hr_module.sql
-- ============================================================

-- ============================================================
-- BEGIN: supabase_phase3c.sql
-- ============================================================
-- =====================================================
-- UNTITLED ADFLUX — PHASE 3C SCHEMA ADDITIONS (IDEMPOTENT)
-- =====================================================
-- RUN THIS ONCE in your Supabase SQL Editor AFTER Phase 2.
-- This file is ADDITIVE and SAFE TO RE-RUN — it drops and
-- recreates policies/triggers/functions so re-running is fine.
--
-- WHAT IT DOES:
--   • Adds approval_status / approved_by / decided_at /
--     rejection_reason / sales_notified_at columns to payments.
--   • Backfills every existing row to approval_status='approved'
--     so historical revenue / incentive numbers don't change.
--   • Rewrites the payment triggers so monthly_sales_data only
--     counts payments where is_final_payment=true AND
--     approval_status='approved'.
--   • Tightens RLS: sales can only INSERT rows with
--     approval_status='pending' and can only EDIT/DELETE their
--     own still-pending rows. Only admins can approve/reject.
--   • Adds dismiss_payment_notification(uuid) RPC so a sales
--     user can clear their rejection banner (SECURITY DEFINER
--     so it can write sales_notified_at under RLS).
-- =====================================================

-- =====================================================
-- 1. NEW COLUMNS (idempotent via IF NOT EXISTS)
-- =====================================================

ALTER TABLE payments
  ADD COLUMN IF NOT EXISTS approval_status    text,
  ADD COLUMN IF NOT EXISTS approved_by        uuid REFERENCES users(id),
  ADD COLUMN IF NOT EXISTS decided_at         timestamptz,
  ADD COLUMN IF NOT EXISTS rejection_reason   text,
  ADD COLUMN IF NOT EXISTS sales_notified_at  timestamptz;

-- Backfill — every pre-existing row is treated as already-approved
-- so we don't nuke historical revenue on the first migration run.
UPDATE payments
   SET approval_status = 'approved'
 WHERE approval_status IS NULL;

-- Lock the column down: NOT NULL + CHECK + DEFAULT 'pending' for
-- any future rows sales sends up.
DO $$ BEGIN
  ALTER TABLE payments ALTER COLUMN approval_status SET NOT NULL;
EXCEPTION WHEN others THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE payments
    ADD CONSTRAINT payments_approval_status_chk
    CHECK (approval_status IN ('pending','approved','rejected'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

ALTER TABLE payments ALTER COLUMN approval_status SET DEFAULT 'pending';

-- Helpful index for the admin "pending" queue.
CREATE INDEX IF NOT EXISTS payments_pending_idx
  ON payments (created_at DESC)
  WHERE approval_status = 'pending';

-- =====================================================
-- 2. REBUILD — rewrite rebuild_monthly_sales so it only
--    counts approved final payments.
-- =====================================================

CREATE OR REPLACE FUNCTION rebuild_monthly_sales(p_staff uuid, p_month text)
RETURNS void AS $$
DECLARE
  new_rev numeric := 0;
  ren_rev numeric := 0;
BEGIN
  SELECT
    COALESCE(SUM(CASE WHEN q.revenue_type = 'new'     THEN q.subtotal ELSE 0 END), 0),
    COALESCE(SUM(CASE WHEN q.revenue_type = 'renewal' THEN q.subtotal ELSE 0 END), 0)
  INTO new_rev, ren_rev
  FROM payments p
  JOIN quotes q ON q.id = p.quote_id
  WHERE p.is_final_payment = true
    AND p.approval_status  = 'approved'   -- NEW: approved only
    AND q.created_by       = p_staff
    AND to_char(p.payment_date, 'YYYY-MM') = p_month;

  INSERT INTO monthly_sales_data (staff_id, month_year, new_client_revenue, renewal_revenue)
  VALUES (p_staff, p_month, new_rev, ren_rev)
  ON CONFLICT (staff_id, month_year)
  DO UPDATE SET
    new_client_revenue = EXCLUDED.new_client_revenue,
    renewal_revenue    = EXCLUDED.renewal_revenue,
    updated_at         = now();
END;
$$ LANGUAGE plpgsql;

-- =====================================================
-- 3. INSERT TRIGGER — replace the old handle_final_payment
--    with one that's aware of approval_status.
-- =====================================================

DROP TRIGGER  IF EXISTS payments_final_trigger ON payments;
DROP FUNCTION IF EXISTS handle_final_payment();

CREATE OR REPLACE FUNCTION handle_payment_insert()
RETURNS TRIGGER AS $$
DECLARE
  staff_uid uuid;
  month_str text;
BEGIN
  -- Only credit revenue when the row lands as approved+final.
  -- (Admins recording payments get approval_status='approved'
  -- from the app; sales inserts come in as 'pending' and will
  -- be credited later via the UPDATE trigger at approval time.)
  IF NEW.is_final_payment = true
     AND NEW.approval_status = 'approved' THEN
    SELECT created_by INTO staff_uid FROM quotes WHERE id = NEW.quote_id;
    month_str := to_char(NEW.payment_date, 'YYYY-MM');
    PERFORM rebuild_monthly_sales(staff_uid, month_str);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS payments_insert_recalc ON payments;
CREATE TRIGGER payments_insert_recalc
  AFTER INSERT ON payments
  FOR EACH ROW EXECUTE FUNCTION handle_payment_insert();

-- =====================================================
-- 4. UPDATE TRIGGER — now also reacts to approval_status
--    transitions (approve / reject / un-approve).
-- =====================================================

CREATE OR REPLACE FUNCTION handle_payment_update()
RETURNS TRIGGER AS $$
DECLARE
  old_counted boolean;
  new_counted boolean;
  old_staff   uuid;
  new_staff   uuid;
  old_month   text;
  new_month   text;
BEGIN
  old_counted := (OLD.is_final_payment = true AND OLD.approval_status = 'approved');
  new_counted := (NEW.is_final_payment = true AND NEW.approval_status = 'approved');

  -- If the row never touched the ledger in either state, no work.
  IF NOT old_counted AND NOT new_counted THEN
    RETURN NEW;
  END IF;

  SELECT created_by INTO old_staff FROM quotes WHERE id = OLD.quote_id;
  SELECT created_by INTO new_staff FROM quotes WHERE id = NEW.quote_id;
  old_month := to_char(OLD.payment_date, 'YYYY-MM');
  new_month := to_char(NEW.payment_date, 'YYYY-MM');

  -- Rebuild OLD side (removes the previous credit cleanly)
  IF old_counted THEN
    PERFORM rebuild_monthly_sales(old_staff, old_month);
  END IF;

  -- Rebuild NEW side (adds the new credit; safe to call even
  -- when staff+month are identical to OLD — rebuild is idempotent)
  IF new_counted
     AND (NOT old_counted OR old_staff <> new_staff OR old_month <> new_month) THEN
    PERFORM rebuild_monthly_sales(new_staff, new_month);
  ELSIF new_counted THEN
    -- Same staff+month: still rebuild once to pick up amount /
    -- quote reassignment edge cases.
    PERFORM rebuild_monthly_sales(new_staff, new_month);
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS payments_update_recalc ON payments;
CREATE TRIGGER payments_update_recalc
  AFTER UPDATE ON payments
  FOR EACH ROW EXECUTE FUNCTION handle_payment_update();

-- =====================================================
-- 5. DELETE TRIGGER — only rebuild if the deleted row was
--    actually contributing (approved + final).
-- =====================================================

CREATE OR REPLACE FUNCTION handle_payment_delete()
RETURNS TRIGGER AS $$
DECLARE
  staff_uid uuid;
  month_str text;
BEGIN
  IF OLD.is_final_payment = true
     AND OLD.approval_status = 'approved' THEN
    SELECT created_by INTO staff_uid FROM quotes WHERE id = OLD.quote_id;
    month_str := to_char(OLD.payment_date, 'YYYY-MM');
    PERFORM rebuild_monthly_sales(staff_uid, month_str);
  END IF;
  RETURN OLD;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS payments_delete_recalc ON payments;
CREATE TRIGGER payments_delete_recalc
  AFTER DELETE ON payments
  FOR EACH ROW EXECUTE FUNCTION handle_payment_delete();

-- =====================================================
-- 6. RLS — sales can only INSERT with approval_status='pending',
--    can only EDIT/DELETE their own still-pending rows, and
--    CANNOT flip their own approval_status.
-- =====================================================

-- Keep admin-all policy; no change needed.

-- Rewrite sales-insert: forces 'pending'
DROP POLICY IF EXISTS "payments_sales_insert_own" ON payments;
CREATE POLICY "payments_sales_insert_own" ON payments FOR INSERT
  WITH CHECK (
    get_my_role() = 'sales'
    AND approval_status = 'pending'
    AND quote_id IN (SELECT id FROM quotes WHERE created_by = auth.uid())
  );

-- Rewrite sales-update: row must be pending AND stay pending
DROP POLICY IF EXISTS "payments_sales_update_own" ON payments;
CREATE POLICY "payments_sales_update_own" ON payments FOR UPDATE
  USING (
    get_my_role() = 'sales'
    AND is_final_payment = false
    AND approval_status  = 'pending'
    AND quote_id IN (SELECT id FROM quotes WHERE created_by = auth.uid())
  )
  WITH CHECK (
    get_my_role() = 'sales'
    AND is_final_payment = false
    AND approval_status  = 'pending'
    AND quote_id IN (SELECT id FROM quotes WHERE created_by = auth.uid())
  );

-- Rewrite sales-delete: only pending rows
DROP POLICY IF EXISTS "payments_sales_delete_own" ON payments;
CREATE POLICY "payments_sales_delete_own" ON payments FOR DELETE
  USING (
    get_my_role() = 'sales'
    AND is_final_payment = false
    AND approval_status  = 'pending'
    AND quote_id IN (SELECT id FROM quotes WHERE created_by = auth.uid())
  );

-- =====================================================
-- 7. RPC — let a sales user clear their rejection banner.
--    SECURITY DEFINER because sales_notified_at would
--    otherwise be blocked by the update policy above
--    (rejected rows are not 'pending', so sales can't UPDATE).
-- =====================================================

CREATE OR REPLACE FUNCTION dismiss_payment_notification(p_payment_id uuid)
RETURNS void AS $$
BEGIN
  UPDATE payments
     SET sales_notified_at = now()
   WHERE id = p_payment_id
     AND approval_status = 'rejected'
     AND quote_id IN (
       SELECT id FROM quotes WHERE created_by = auth.uid()
     );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

GRANT EXECUTE ON FUNCTION dismiss_payment_notification(uuid) TO authenticated;

-- =====================================================
-- DONE. No existing revenue numbers were changed.
-- Safe to re-run this whole file again if anything errors.
-- =====================================================

-- ============================================================
-- END: supabase_phase3c.sql
-- ============================================================

-- ============================================================
-- BEGIN: supabase_phase3d.sql
-- ============================================================
-- =====================================================
-- UNTITLED ADFLUX — PHASE 3D: TEAM LEADERBOARD RPC
-- =====================================================
-- RUN THIS ONCE in your Supabase SQL Editor AFTER Phase 3C.
-- Safe to re-run — the function is dropped+recreated on every run.
--
-- WHY THIS EXISTS:
--   Sales reps couldn't see correct leaderboard numbers for
--   other reps because RLS on staff_incentive_profiles and
--   monthly_sales_data limits each user to their own rows.
--   Computing per-rep forecast/earned client-side meant every
--   other rep showed ₹0 in their teammates' views.
--
-- WHAT IT DOES:
--   Returns one row per active sales user with the raw inputs
--   the JS calculateIncentive() needs:
--     • Their incentive profile rates (with settings fallback)
--     • Their monthly_sales_data revenue summed across the
--       requested month_keys
--     • Their open pipeline subtotals (sent/negotiating/draft)
--     • Their won-unsettled subtotals (won + no final approved
--       payment)
--     • Their lifetime won-quote count
--   The JS layer plugs these into calculateIncentive twice
--   (earned + forecast/proposed) so the math stays in one place.
--
-- NOTE ON SCHEMA QUALIFICATION:
--   Every table reference is explicitly prefixed with `public.`.
--   Earlier attempts relied on the function's `SET search_path`
--   attribute, but that only changes the runtime search_path —
--   the parser still uses the SESSION search_path at CREATE
--   time, and Supabase SQL Editor sessions don't always include
--   public. Hard-coding the prefix removes that dependency.
--
-- SECURITY:
--   SECURITY DEFINER bypasses RLS so the aggregates can be read
--   regardless of caller. Only AGGREGATES are returned — no
--   individual quote, payment, or salary rows leak. Profile
--   rates and salary leak indirectly via the proposed-incentive
--   calculation (rep B can infer rep A's rates from the math),
--   which is the same level of transparency the existing
--   settled-revenue leaderboard had.
-- =====================================================

DROP FUNCTION IF EXISTS public.get_team_leaderboard(text[]);

CREATE OR REPLACE FUNCTION public.get_team_leaderboard(p_month_keys text[])
RETURNS TABLE(
  user_id          uuid,
  name             text,
  monthly_salary   numeric,
  sales_multiplier numeric,
  new_client_rate  numeric,
  renewal_rate     numeric,
  flat_bonus       numeric,
  msd_new          numeric,
  msd_renewal      numeric,
  open_new         numeric,
  open_renewal     numeric,
  wu_new           numeric,
  wu_renewal       numeric,
  won_count        bigint
)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  WITH s AS (
    SELECT
      default_multiplier,
      new_client_rate    AS s_new_rate,
      renewal_rate       AS s_ren_rate,
      default_flat_bonus AS s_flat
    FROM public.incentive_settings
    LIMIT 1
  )
  SELECT
    u.id                                         AS user_id,
    u.name                                       AS name,
    COALESCE(p.monthly_salary, 0)                AS monthly_salary,
    COALESCE(p.sales_multiplier, (SELECT default_multiplier FROM s), 5)        AS sales_multiplier,
    COALESCE(p.new_client_rate,  (SELECT s_new_rate          FROM s), 0.05)    AS new_client_rate,
    COALESCE(p.renewal_rate,     (SELECT s_ren_rate          FROM s), 0.02)    AS renewal_rate,
    COALESCE(p.flat_bonus,       (SELECT s_flat              FROM s), 10000)   AS flat_bonus,
    -- monthly_sales_data summed across the requested period months
    COALESCE((
      SELECT SUM(new_client_revenue)
      FROM public.monthly_sales_data
      WHERE staff_id = u.id
        AND month_year = ANY(p_month_keys)
    ), 0) AS msd_new,
    COALESCE((
      SELECT SUM(renewal_revenue)
      FROM public.monthly_sales_data
      WHERE staff_id = u.id
        AND month_year = ANY(p_month_keys)
    ), 0) AS msd_renewal,
    -- open pipeline = quotes not in lost/won, by revenue_type
    COALESCE((
      SELECT SUM(subtotal) FROM public.quotes
      WHERE created_by = u.id
        AND status NOT IN ('lost','won')
        AND revenue_type = 'new'
    ), 0) AS open_new,
    COALESCE((
      SELECT SUM(subtotal) FROM public.quotes
      WHERE created_by = u.id
        AND status NOT IN ('lost','won')
        AND revenue_type = 'renewal'
    ), 0) AS open_renewal,
    -- won-unsettled = status='won' AND no final approved payment
    COALESCE((
      SELECT SUM(q.subtotal) FROM public.quotes q
      WHERE q.created_by = u.id
        AND q.status = 'won'
        AND q.revenue_type = 'new'
        AND NOT EXISTS (
          SELECT 1 FROM public.payments p2
          WHERE p2.quote_id = q.id
            AND p2.is_final_payment = true
            AND p2.approval_status  = 'approved'
        )
    ), 0) AS wu_new,
    COALESCE((
      SELECT SUM(q.subtotal) FROM public.quotes q
      WHERE q.created_by = u.id
        AND q.status = 'won'
        AND q.revenue_type = 'renewal'
        AND NOT EXISTS (
          SELECT 1 FROM public.payments p2
          WHERE p2.quote_id = q.id
            AND p2.is_final_payment = true
            AND p2.approval_status  = 'approved'
        )
    ), 0) AS wu_renewal,
    -- lifetime won quote count
    COALESCE((
      SELECT COUNT(*) FROM public.quotes
      WHERE created_by = u.id
        AND status = 'won'
    ), 0) AS won_count
  FROM public.users u
  LEFT JOIN public.staff_incentive_profiles p ON p.user_id = u.id
  WHERE u.role = 'sales'
$$;

GRANT EXECUTE ON FUNCTION public.get_team_leaderboard(text[]) TO authenticated;

-- =====================================================
-- DONE. Test in SQL Editor:
--   SELECT * FROM public.get_team_leaderboard(ARRAY['2026-04']);
-- =====================================================

-- ============================================================
-- END: supabase_phase3d.sql
-- ============================================================
