-- =====================================================================
-- ADFLUX → UNTITLED OS  •  PHASE 103.D.6 SQL
-- compute_daily_ta — drift floor 100m -> 10m (accurate km for dense pings)
-- 2026-05-31 (Brijesh Solanki)
-- =====================================================================
--
-- WHY:
--   The Phase 103.D.3 native foreground service writes a GPS fix every
--   ~20s (vs the old sparse 5-min pings). The 100m segment floor (Phase
--   68) was tuned for sparse data; with dense pings, real city / slow
--   driving makes <100m segments that the 100m floor wrongly DROPS, so
--   km massively under-counts (Dixita's 10.7 km Google drive → 7.0 km
--   server / 3.6 km truncated display).
--
--   CALIBRATED against that exact drive (1901 segments, accuracy<=50m,
--   speed<=120 km/h):
--       raw, no floor : 41.64 km   (pure jitter — far too high)
--       >= 10 m floor : 10.79 km   ← matches Google's 10.7
--       >= 25 m floor :  8.14 km
--       >= 35 m floor :  7.75 km
--       >= 100 m floor:  7.04 km   (current — under-counts)
--   The 10 m floor cleanly separates real movement from GPS jitter.
--   Client gpsDistance.js MIN_SEG_KM moves to 0.010 in the SAME commit.
--
-- WHAT THIS CHANGES (ONE line):
--   Line `IF v_seg_km >= 0.10 ...` → `>= 0.010`. Everything else in the
--   function is the live Phase 97.2 body VERBATIM — the
--   _assert_self_or_admin gate, the approved-claim merge (Phase 36.8),
--   the ta_override, city detection, daily_ta upsert. Nothing else moves.
--
-- WHAT THIS DOES NOT TOUCH:
--   - The TA payout FORMULA (km × bike_rate + DA + hotel) — unchanged.
--   - The Phase 34Z.67 trigger that calls this on gps_pings INSERT.
--   - accuracy filter (50m), speed cap (120 km/h), daily logic.
--
-- MONEY NOTE: TA payable rises toward accurate km for reps on the dense
--   service (they were under-counted). This is a data-accuracy fix, not
--   a rate change. Verify daily_ta.km_traveled vs a real drive before
--   the month-end TA payout.
-- =====================================================================

-- -------------------------------------------------------------------------
-- compute_daily_ta REMOVED from this file (Phase 178).
-- Canonical: db/functions/compute_daily_ta.sql  (MONEY function — TA payout)
-- Do NOT re-add it here. Edit the canonical file only (§71). Trigger wiring
-- (per-ping TA recompute + claim-approve) stays in the phase files.
-- -------------------------------------------------------------------------


NOTIFY pgrst, 'reload schema';


-- =====================================================================
-- VERIFY
-- =====================================================================
-- V1: the floor is now 0.010 (not 0.10) in the live function
--   SELECT pg_get_functiondef('public.compute_daily_ta(uuid,date)'::regprocedure)
--     LIKE '%v_seg_km >= 0.010%' AS floor_is_10m;
--   Expected: true.
--
-- V2: recompute Dixita today + check km matches the calibration (~10.79)
--   SELECT public.compute_daily_ta('caa6236a-844b-4097-8d93-f71d9b28ffae', '2026-05-31');
--   SELECT km_traveled, gps_pings_count FROM public.daily_ta
--    WHERE user_id='caa6236a-844b-4097-8d93-f71d9b28ffae' AND ta_date='2026-05-31';
--   Expected: km_traveled ≈ 10.79 (was ~7.04 at the 100m floor).
--   NOTE: only recomputes if the row is still status='pending'.
--
-- =====================================================================
-- ROLLBACK
-- =====================================================================
--   Re-run supabase_phase97_2_rpc_role_gates.sql section 5.5 (the
--   0.10 version), OR change 0.010 back to 0.10 here and re-run.
-- =====================================================================
