-- supabase_phase311_quote_won_at.sql — SUPERSEDED (2026-08-21).
--
-- The quotes.won_at column + trigger + backfill now live in ONE consolidated,
-- idempotent file:  supabase_phase311_final.sql  (which also adds leads.won_at).
--
-- Do NOT run this file. Its original backfill dated PAID deals by their final
-- payment_date (settled month), not the WON month — supabase_phase311_final.sql
-- corrects that. Run supabase_phase311_final.sql instead.
